module.exports={
    clientDropdown : "//span[contains(text(), 'Company:')]",
    selectClient : "//div[text() = '<<param>>']",
    hyperlinkPath : "//a[text() = '<<param>>']",
    allProjectsPath : "//span[text()='<<param>>']",
    companyNameLink : "//span[text()='<<param>>']",
    dropdownPath : "//div[contains(@class,'label') and text()='<<param>>']//following::div[1]//div[contains(@class, '-container')]",
    dropdownInput: "//div[contains(@class,'label') and text()='<<param>>']//following::input[1]",
    dropdownSelection : "//div[contains(@class,'label') and text()='<<param>>']//following::div[@class=' css-t2mbhx-menu']//div[text()='<<param>>']",
    dropdownSelectAll : "//div[@class='label' and text()='<<param>>']//following::div[@class=' css-t2mbhx-menu']//span[text()='SELECT ALL']",
    dropdownUnselectAll : "//div[@class='label' and text()='<<param>>']//following::div[@class=' css-t2mbhx-menu']//span[text()='UNSELECT ALL']",
    emptyDropdown : "//div[@class='label' and text()='<<param>>']//following::div[text()='<<param>>']",
    clickAnywhere : "//div[@class='label' and text()='Project*:']",
    button : "//button[text()='<<param>>']",
    hyperlink : "//div[@class='export-link' and text()='<<param>>']",
    emGroupNone : "//div[text()='EM Application:']//preceding::div[text()='None']",
    emApplicationNone : "//div[text()='EM Application:']//following::div[text()='None']",
    inputFieldPath : "//div[contains(@class,'label') and text()='<<param>>']//following::div[1]//input",
    emApplicationSearch : "//span[text()='<<param>>']",
    emSearchInputField : "//input[contains(@name ,'text')]",
    clickEmGroup : "//a[contains(@class, 'expend-link') and text()='<<param>>']",
    editUserspath : "//a[@class='expend-link' and text()]",
    userPrivilegeOption: "//a[text()='<<param>>']//following::span[text()='<<param>>']",
    editPath : "//a[contains(@href, '<<param>>')]",
    tableHeader : "//div[@class='' and text()='<<param>>']",
}