module.exports = {
    pageTitle: "//div[@class='title' and contains(text(), '<<param>>')]",
    tableHeader: "//div[contains(@class, 'rt-thead')]//div[@role='button']//div[text()='<<param>>']",
    companyDropdown: "//div[@data-qa = 'dropDownControl']",
    companyMenu: "//div[@class='company-container']//div[@role='menu']//div[@role='menuitem' and @data-qa='<<param>>']",
    emailField: "//div[contains(text(), 'E-mail')]//following::input",
    emailValidMsg: "//div[contains(text(), '<<param>>')]",
    projectDropdown: "//div[@class='label' and contains(text(), 'Projects:')]//following::div[contains(@class, 'control')]//div[contains(@class, 'Indicators')]",
    projectsMenu: "//div[contains(@class, 'menu')]//div[text()='<<param>>']",
    projectsSelectAll: "//div[contains(@class, 'menu')]//span[text()='<<param>>']",
    permissionDropdown: "//div[@class='label' and contains(text(), 'Permissions')]//following::div[contains(@class, 'control')]",
    addButton: "//button[@name='add-button']",
    message: "//div[contains(@class, 'success warning')]//div[contains(text(), '<<param>>')]",
    errorMsg: "//div[contains(@class, 'error warning')]//div[contains(text(), '<<param>>')]",
    emailLink: "//span[contains(text(), '<<param>>')]",
    navMenu: "//div[@data-qa='navMenu']",
    logOut: "//div[@data-qa='Log Out']",
    button: "//button[contains(text(), '<<param>>')]",
    text: "//div[contains(text(), '<<param>>')]",
    tile: "//a[contains(text(), '<<param>>')]",
    rowOption: "//option[contains(text(), '<<param>>')]",
    subTile: "//li[contains(text(), '<<param>>')]",
    projectAdminCheckbox: "//div[contains(@class, 'proj-permission-container')]//div[@class='data-row']//div[contains(@class, 'col')][2][../div//span='<<param>>']",
    userCheckbox: "//div[contains(@class, 'rt-table')]//div[@role='rowgroup']//div[contains(@class, 'rt-td')][1][../div//span='<<param>>']",
    actionDropdown: "//div[contains(text(),'Actions')]//following::div[contains(@class,'control')]/div[contains(@class, 'Indicators')]",
    errorMsg2: "//div[contains(@class, 'error warning')]//span[contains(text(), '<<param>>')]",
    permissionCheckbox: "//div[contains(@class, 'permission-field-wrapper')]//preceding-sibling::div//label[../../div//div[contains(text(), '<<param>>')]]",
    checkbox: "//span[contains(normalize-space(), '<<param>>')]//parent::label//*[name()='rect']"
};
