module.exports={
    folder: "//div[contains(text(),'<<param>>')]",
    expandIcon: "//div[contains(text(),'<<param>>')]/ancestor::div[@data-testid='withNodeActions']//div[@data-testid='expandable-port']//*[name()='svg']",
    addIcon: "//div[contains(text(),'<<param>>')]/ancestor::div[@data-testid='withNodeActions']//div[@data-testid='add-new-node-icon']//*[name()='svg']",
    newNodeRadio: "//div[contains(text(),'<<param>>')]/ancestor::label/*[name()='svg']",
    newNodeName: "//div[contains(text(),'Node name')]/parent::div/parent::div//input",
    newNodeDescription: "//div[contains(text(),'Description')]/parent::div/parent::div//textarea",
    newNodeAddButton: "//button[contains(text(),'ADD')]",
    newNodeCancelButton: "//button[contains(text(),'CANCEL')]",
    button: "//button[contains(text(),'<<param>>')]",
    botMessageResponse: "//body[@id='tinymce']",
    botMessageOptions: "//div[contains(text(),'<<param>>')]/preceding-sibling::button",
    botMessageMenuOptionButton: "//div[contains(text(),'Menu option')]",
    botMessageMenuAddButton: "//button[@aria-label='Add']",
    botMessageNewMenuInput: "//label[contains(text(),'<<param>>')]/following-sibling::div//input",
    botMessageNewMenuTextarea: "//label[contains(text(),'<<param>>')]/following-sibling::div//textarea",
    botMessageNewMenuSelectDropdown: "//label[contains(text(),'<<param>>')]/following-sibling::div//*[name()='svg']",
    botMessageNewMenuSelectItem: "//*[contains(text(),'<<param>>')]",
    botMessageAction: "//div[@data-testid='withNodeActions']//div[@data-qa='dropDownControl']//*[name()='svg']",
    actionMenu: "//div[@data-testid='withNodeActions']//div[contains(@data-qa,'<<param>>')]",
    nodeActionDropdown: "//div[contains(text(),'<<param>>')]/ancestor::div[@data-testid='withNodeActions']//div[@data-qa='dropDownControl']//*[name()='svg']",
    addUtterance: "//div[contains(text(),'ADD NEW')]",
    addUtteranceInput: "//div[contains(text(),'ADD NEW')]/parent::button/following-sibling::div//input",
    addUtteranceConfirm: "//div[contains(text(),'ADD NEW')]/parent::button/following-sibling::div//div[@role='gridcell']//button[@title='Confirm']",
    tabName: "//li[contains(@id,'tab_<<param>>')]",
    selectAPIDropdown: "//div[contains(text(),'Select API')]/parent::div/following-sibling::div//*[name()='svg']",
    selectAPIValue: "//*[contains(text(),'<<param>>')]",
    addNodeButton: "//div[contains(text(),'Add node')]",
    linkToNodeDropdown: "//label[contains(text(),'Link to node')]/parent::div//*[name()='svg']",
    selectNode: "//*[contains(text(),'<<param>>')]",
    doneButton: "//button[contains(text(),'DONE')]"
  }