module.exports={
    viewClient : "//span[text()=' EM Applications for : ']",
    getClient : "//div[normalize-space()='<<param>>']",
    inputField : "//div[contains(@class,'link') and contains(text(),'<<param>>')]//following::input[1]",
    inputFieldSchedule : "//div[contains(@class,'pb') and contains(text(),'<<param>>')]//following::input[1]",
    tableHeader : "//div[contains(@class,'rt-thead')]//div[contains(text(),'<<param>>')]",
    hyperlinkPath : "//a[normalize-space()='<<param>>']",
    dropdownPath : "//div[contains(@class,'') and contains(text(),'<<param>>')]//following::div[1]//div[contains(@class, '-container')]",
    dropdownSelect : "//div[contains(@class,'') and contains(text(),'<<param>>')]//following::div[@class=' css-t2mbhx-menu']//div[contains(text(),'<<param>>')]",
    emAppNamePath :"//div[contains(@class, 'label') and contains(text(),'<<param>>')]",
    expandCollapsePath : "//a[contains(@class, 'link') and text() = '<<param>>']",
    textName : "//div[contains(text(),'<<param>>')]",
    button : "//button[contains(normalize-space(),'<<param>>')]",
    warning : "//span[contains(normalize-space(),'<<param>>')]",
    textareaPath : "//div[contains(text(),'<<param>>')]//following::textarea[1]",
    checkboxPath : "//div[contains(text(),'<<param>>')]//preceding::*[name()='rect' and contains(@x,'0.5')]",
    deployedSnapshot : "//div[@class='col'][normalize-space()='<<param>>']",
    firstOperation : "(//div[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[1]",
    secondOperation : "(//div[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[2]",
    thirdOperation : "(//div[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[3]",
    fourthOperation : "(//div[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[4]",
    fifthOperation : "(//div[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[5]",
    deletePath : "(//div[contains(text(), '<<param>>')]//following::span[contains(text(),'DELETE')])[1]",
    scheduleView : "(//span[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[1]",
    scheduleEdit : "(//span[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[2]",
    scheduleDate : "(//span[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[3]",
    scheduleDefault : "(//span[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[4]",
    scheduleDelete : "(//span[contains(text(),'<<param>>')]//following::a[contains(@href, '/services/em')])[5]",
    dateInput : "//div[contains(@class,'text') and contains(text(),'<<param>>')]//following::input[1]",
    calenderPath: "//button[@type='button']//span[contains(@class, 'rdrSelected')]//following::span[3]",
    firstCheckbox: "(//div[contains(text(),'<<param>>')]//preceding::input[@type='radio'])[1]",
    secondCheckbox: "(//*[name()='rect' and contains(@stroke,'#B2B2B2')])[1]",
    thirdCheckbox: "(//*[name()='rect' and contains(@stroke,'#B2B2B2')])[2]",
    defaultSchedule : "//div[@class='text-label'][normalize-space()='<<param>>']",
    changeTypeDrop : "(//*[contains(text(),'<<param>>')]//preceding::div[1]//*[name()='svg'])[1]",
    historyPath : "//*[contains(text(),'<<param>>')]/following::div[contains(text(),'<<param>>')]",
    headerPathFirst : "//div[@class='collapse show']//div//div[contains(text(),'<<param>>')]",
    headerPath : "//div[@class='collapse show']//div//span[contains(text(),'<<param>>')]",              
}
