module.exports ={
selectClient: "//div[@class='css-0']//*[name()='svg']",
telephonyTab: "//*[@id='<<param>>']",
clientName: "//div[normalize-space()='<<param>>']",
verifyClient : "//div[@class='company-container']//*//span[normalize-space()='Manage Numbers for:']//following-sibling::span",
viewOtherParameter: "//div[contains(@class,'input mar-l-5')]//*//div[contains(@class,'css-2b097c-container')]",
vopDropDown: "//div[contains(@class,'css-1px2sv3-ReactDOMBlockingRoot')]",
multipleSelectValue: "//div[@class='css-1ql6bwf-multiValue']//div",
multipleSelect: "//div[@class='css-1ql6bwf-multiValue']",
applicationSelection: "//div[contains(@id,'<<param>>')]",
telephonyProperties: "//span[normalize-space()='<<param>>']",
projectDefaultValue: "//div[@class='search-container']//child::div[2]//*//div[contains(@class,'css-1uccc91-singleValue')]",
projectDropDown: "//div[@class='search-container']//child::div[2]//*//div[contains(@class,'css-1dry2jn-control')]",
selectProject: "//div[contains(@id,'<<param>>')]",
singleProjectValue: "//div[@class='search-container']//child::div[2]//*//span",
automationProject: "//div[@class='cell'][normalize-space()='Automation-Project2']",
checkFilteredProject: "//div[@class='rt-table']//*//div[contains(@class, '-odd')]//div[3]//div[@class='cell']",
searchFilter: "//input[@name='tfs-textfield']",
searchButton: "//button[normalize-space()='<<param>>']",
selectAllButton: "//input[@id='<<param>>']",
project2Select: "//*[text()='dialog@automationproject2.automation.com.notifier.sip.tellme.com']//parent::span//parent::div//preceding-sibling::div//input",
project3Select: "//input[@id='select-17153']",
actionsInput: "//div[contains(@class,'actions-container')]//*//input",
selectAction: "//div[contains(@class,'actions-container')]//*//input/parent::div",
actionsEditDetails: "//div[contains(@id, '<<param>>')]",
editTitle: "//div[contains(@class, 'heading-content')]//div[@class='title']",
parentWarning: "//div[@class='warning-item']//div",
telephonyNumber: "//*[text()='<<param>>']//parent::span//parent::div/preceding-sibling::div//input[@type='checkbox']",
bulkEditDialog: "//div[@class='css-v8oppp']//span",
cancelBulkEditDialog: "//div[@class='css-10a73ai']//div[@role='button']//*[name()='svg']",
reorganizeProjectDialogue: "//div[@class='dialog-container']//*//span[normalize-space()='Reorganize to Project']",
selectReorganizeProject: "//div[contains(@class,'<<param>>')]//*//div[contains(@class, 'css-1dry2jn-control')]",
clickReorganizeProjectDropdown: "//div[contains(@class,'<<param>>')]//*//div[contains(@class,'css-2b097c-container')]",
reOrganizeSelectProject: "//div[contains(@id, '<<param>>')]",
okButton: "//button[@name='tfs-dialog-ok-key']",
changedReoraganizedProject: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div//div[@class='cell']",
stateNameStatus: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[6]",
descriptionInput: "//input[@name='description']",
descriptionStatus: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[2]",
descriptionText: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[2]//*//input[@type='text']",
agreeCheckBox:"//div[@class='terms']//label//*[name()='svg']",
showPastUses:"//div[contains(@class,'<<param>>')]//*//label",
pastUseTelephoneNumber:"//*[text()='<<param>>']",
transferPromptStatus: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[6]",
transferPromptText: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[6]//*//input",
errorPromptStatus: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[7]",
errorPromptText: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[7]//*//input",
backupTransferStatus:"//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[8]",
backupTransferText: "//*[text()='<<param>>']//parent::span//parent::div/following-sibling::div[8]//*//input[@type='text']",
saveButton: "//button[@name='<<param>>']",
applicationProperties: "//div[@class='heading-container']/following-sibling::div[1]//*//div[@class='form-container']//child::<<param>>//*//div[@class='label']",
telephonePropertiesExpandLink: "//div[@class='heading-container']/following-sibling::<<param>>//*//a[contains(@class,'expend-link')]",
errorHandlingProperties: "//div[@class='heading-container']/following-sibling::div[2]//*//div[@class='form-container']//child::<<param>>//*//div[@class='label']",
reportingGroupProperties: "//div[@class='heading-container']/following-sibling::div[3]//*//div[@class='form-container']//child::<<param>>//*//div[@class='label']",
networkProperties: "//div[@class='heading-container']/following-sibling::div[4]//*//div[@class='form-container']//child::<<param>>//*//div[@class='label']",
}
