module.exports={
    mainMenu: "//a[contains(text(),'<<param>>')]",
    agentTabs: "//span[contains(text(),'<<param>>')]",
    activeInteractionsAlertOk: "//div[contains(text(),'Active Interactions')]/following-sibling::center/a[contains(text(),'OK')]",
    createIcon: "//li[contains(@title,'Create')]/a",
    adminStackContainer: "//div[@id='adminStackContainer']",
    entryName: "//td[contains(text(),'<<param>>')]",
    filterLink: "//a[contains(@class,'filter') and contains(text(),'Filter')]",
    filterColumn: "//span[contains(text(),'Any Column')]//ancestor::td/following-sibling::td/input",
    filterColumnValue: "//td[contains(@class,'dijitMenuItemLabel') and contains(text(),'<<param>>')]",
    filterCondition: "//span[contains(text(),'contains')]//ancestor::td/following-sibling::td/input",
    filterConditionValue: "//td[contains(@class,'dijitMenuItemLabel') and contains(text(),'<<param>>')]",
    filterValueInput: "//span[contains(text(),'Value')]/following-sibling::div//input",
    filterButton: "//span[contains(@aria-label,'Submit the filter')]",
    fieldValue: "//label[contains(text(),'<<param>>')]/following-sibling::input",
    button: "//a[contains(text(),'<<param>>')]",
    selectTab: "//span[contains(text(),'<<param>>')]",
    tabAddIcon: "//a[contains(@title,'Add')]",
    tabCheckbox: "//td[contains(text(),'<<param>>')]/preceding-sibling::td/div",
    addSkillButton: "//div[contains(@id,'dijit_Dialog_5')]//a[contains(text(),'<<param>>')]",
    addFailure: "//span[contains(text(),'addition Failed!')]",
    skillsTabHeader: "//label[contains(text(),'Please select the Skills')]",
    dropdownIcon: "//label[contains(text(),'<<param>>')]/following-sibling::table[1]/tbody[1]/tr[1]/td[2]/input[1]",
    dropdownValue: "//tr[contains(@aria-label,'<<param>>')]",
    addUserSkillButton: "//div[contains(@id,'dijit_Dialog_2')]//a[contains(text(),'<<param>>')]",
    addUserTeamActionIcon: "//label[contains(text(),'List of team')]/following-sibling::a[contains(@title,'<<param>>')]",
    addUserTeamButton: "//div[contains(@id,'dijit_Dialog_3')]//a[contains(text(),'<<param>>')]",
    popupAddButton: "//div[contains(@class,'dijitFocused')]//a[contains(text(),'<<param>>')]"
  }